const files = [
  './src/Avatar/index.tsx',
  './src/Badge/index.tsx',
  './src/Balloon/index.tsx',
  './src/Button/Button.tsx',
  './src/Button/index.tsx',
  './src/Button/LinkButton.tsx',
  './src/Checkbox/index.tsx',
  './src/Container/index.tsx',
  './src/Cursor/index.tsx',
  './src/Dialog/index.tsx',
  './src/Dropdown/index.tsx',
  './src/Icon/Icon.tsx',
  './src/Icon/index.tsx',
  './src/Icon/PixelArts.tsx',
  './src/Icon/ReactionIcon.tsx',
  './src/Icon/SNSIcon.tsx',
  './src/Input/index.tsx',
  './src/List/index.tsx',
  './src/Progress/index.tsx',
  './src/Radio/index.tsx',
  './src/Table/index.tsx',
  './src/Tag/index.tsx',
  './src/Text/index.tsx',
  './src/Textarea/index.tsx',
];
export default files;
