// Import global CSS. This path should be accessible during Storybook build/dev.
// Since vite.config.ts copies src/assets/nes.css to lib/assets/nes.css,
// and Storybook runs from the project root, this import should resolve correctly
// IF components are expected to import it this way OR if it's for Storybook's own UI.
// However, for components in the library, they might rely on CSS modules or
// the lib consumer to include nes.css.
// For Storybook's own preview area, importing it here makes sense.
import '../src/assets/nes.css';

// Attempt to migrate setConsoleOptions
// The addon-console might pick up parameters automatically or via a dedicated parameter.
// Checking addon-console documentation, it seems it might not need explicit setup here anymore for panelExclude.
// If console filtering is needed, it can be set using `parameters.console`.
// For now, we'll omit explicit setConsoleOptions as it was from Storybook v5 structure.

export const parameters = {
  // actions: { argTypesRegex: "^on[A-Z].*" }, // Default in addon-essentials
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  // Example for console addon parameter if needed:
  // console: {
  //   panelExclude: [],
  // },
  docs: {
    // Ensures that the docs addon is configured (though autodocs in main.js is the primary switch)
  }
};

// Global decorators can be added here if needed.
// The `withPropsTable` from storybook-addon-react-docgen is not used with Vite.
// Component documentation (props tables) should be generated by addon-docs with react-vite.
export const decorators = [
  // Add any global decorators from the old config if they are still relevant
  // e.g., if there was a global wrapper component
];
